function [fitresult, gof] = createFit(ddt, ddi)
%CREATEFIT(DDT,DDI)
%  Create a fit.
%
%  Data for 'test' fit:
%      X Input : ddt
%      Y Output: ddi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Sep-2013 15:03:10


%% Fit: 'test'.
[xData, yData] = prepareCurveData( ddt, ddi );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'test' );
h = plot( fitresult, xData, yData );
legend( h, 'ddi vs. ddt', 'test', 'Location', 'NorthEast' );
% Label axes
xlabel( 'ddt' );
ylabel( 'ddi' );
grid on


